antora-playbook.yml

For now, we only have the structure of the documentation but content is
coming.
@gastaldi I had no idea how to test this change? Let's see if we have GH Actions kicking in :).

Add quarkiverse-github-app extension

---

antora-playbook.yml

This branch add quarkus-mockk repo to the quarkiverse documentation

Add Quarkus MockK documentation

---

antora-playbook.yml

This is to address https://github.com/quarkiverse/quarkus-cxf/issues/220

Added v* to list of quarkus-cxf branches

---

antora-playbook.yml

Reverts quarkiverse/quarkiverse-docs#11

Revert "Added v* to list of quarkus-cxf branches"

---

antora-playbook.yml

Fixes https://github.com/quarkiverse/quarkus-cxf/issues/220

 Added v* to list of quarkus-cxf branches

---

antora-playbook.yml

Addresses https://github.com/quarkiverse/quarkus-cxf/issues/268

Added v0.9 branch for quarkus-cxf

---

antora-playbook.yml

I have added docs for the quarkus-logging-json extension.

Added quarkus-logging-json docs

---

antora-playbook.yml

Reverts quarkiverse/quarkiverse-docs#40

Revert "add Quarkus Java Embedded Framework to Quarkus docs"

---

antora-playbook.yml

Fixes https://github.com/quarkiverse/quarkus-jackson-jq/issues/40

Add quarkus-jackson-jq

---

antora-playbook.yml

Just noticed that I missed a PR to this file!

Adding Dashbuilder Quarkus Extension

---

antora-playbook.yml

Issue: https://github.com/quarkiverse/quarkus-poi/issues/17

Added branch 1.x for quarkus-poi

---

antora-playbook.yml

- Fixes #97
- Used the following command to sort entries: `yq ea '.| .content.sources | sort_by(.url) ' antora-playbook.yml`

Order antora-playbook.yml entries

---

antora-playbook.yml

Reference: https://github.com/quarkusio/quarkus/issues/37843

Add the Quarkus Kiota extension

---

antora-playbook.yml

Fixed version of [this](https://github.com/quarkiverse/quarkiverse-docs/pull/130)

Add Quarkus Kiota docs location

---

antora-playbook.yml

Revert when https://github.com/quarkiverse/quarkus-openapi-generator/issues/669 is resolved

Remove openapi-generator temporarily

---

antora-playbook.yml

@gastaldi Didn't worked as expected with HEAD.

Fix refname for Quarkus Amazon Service (#145)

---

antora-playbook.yml

Reverts quarkiverse/quarkiverse-docs#144

Revert "Remove openapi-generator temporarily"

---

antora-playbook.yml

- Fixes https://github.com/quarkiverse/quarkus-oidc-proxy/issues/5

Add quarkus-oidc-proxy

---

antora-playbook.yml

- add branch 3.2.x
- remove branches 3.0.x and 3.1.x
- add tags 3.0.7 and 3.1.6

quarkus-artemis:

---

antora-playbook.yml

https://github.com/quarkiverse/quarkus-easy-retrofit

add quarkus-easy-retrofit to antora-playbook.yml

---

.github/workflows/alphabetise.yml

Not sure I could spot the error, but I've tidied up the indenting, which hopefully will fix it.

Fix syntax error (maybe) in alphabetise workflow

---

.github/workflows/alphabetise.yml

Hopefully will fix the error in https://github.com/quarkiverse/quarkiverse-docs/actions/runs/10308937259. 
I went for github_actor as the user.

Set github user details

---

antora-playbook.yml

I created this PR with the wrong order to intentionally test #173

Add quarkus-backstage

---

.github/workflows/alphabetise.yml

Fixes (I hope) https://github.com/quarkiverse/quarkiverse-docs/actions/runs/10310002583

Do not fail the workflow if the file was already alphabetised

---

antora-playbook.yml

Update antora-playbook.yml with Quarkus Presidio

Update antora-playbook.yml with Quarkus Presidio

---

package.json

I've done it as a "post***" to make sure we override whatever was initially unpacked from the theme 🤞🏻

Download the most recent Search components script version after the site is generated

---

antora-playbook.yml

According to https://docs.antora.org/antora-ui-default/template-customization/#page-pagination-attribute
- Fixes https://github.com/quarkiverse/antora-ui-quarkiverse/issues/108

Enable pagination in the page footer

---

antora-playbook.yml

Add quarkus-docling to the main documentation

Add quarkus-docling
